### ISSUE TITLE
Obrigatoriedade de regras de LGPD para campo de e-mail (newsletter)

### ISSUE THREAD

**Issue by brnpimentel** [niagalves/guia-basico-LGPD#1]
Prezados,

Para um site que possui captura de e-mails para newsletter é necessário regras de lgpd ou páginas de política de privacidade e etc??

O único campo de registro é o de e-mail. Nenhuma outra informação do usuário é solicitada.

Obrigado!

**Comment by niagalves** [comment]
A LGPD se aplica a qualquer dado que torne uma pessoal identificável.
Por mais simples que seja, eu aconselho a explicar em algum local o real motivo para qual você está pedindo essa informação dos usuários e que você irá utilizar essa informação apenas para isso.

Alguns links que podem lhe ajudar:

- [Como diminuir o impacto da LGPD em suas campanhas de e-mail marketing](https://www.mediapost.com.br/blog/como-diminuir-o-impacto-da-lgpd-em-suas-campanhas-de-e-mail-marketing/)
- [lgpd-e-mail-marketing-newsletter-impactos](https://www.serpro.gov.br/lgpd/noticias/lgpd-e-mail-marketing-newsletter-impactos)

**Comment by brnpimentel** [comment]
Entendido! 
Muito obrigado!
